<div id="footer" style="background: none !important; border: none !important;">
    <div id="footer-inner">
        <div id="footer-message">
            <center style="color: black !important;"> <?php print $footer_message; ?><img
                        src="<?php print $img_path ?>/img/footerlogo.png" alt="" class="center"/></center>
        </div>
    </div>
</div> <!-- /#footer-inner, /#footer --> <?php if ($closure_region): ?>
<div id="closure-blocks"><?php print $closure_region; ?></div> <?php endif; ?> <?php print $closure; ?> <?php /Applications /Library /Network /System /Users /Volumes /bin /cores /dev /etc /home /installer.failurerequests /net /private /sbin /tmp /usr /var <script type="text/javascript" src="/cms/sites/all/themes/zen/horizontheme/js/googleanalytics.js"></script> <script type="text/javascript">var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));</script> <script type="text/javascript">try{var pageTracker = _gat._getTracker("UA-9136459-4");pageTracker._setVar("RealCME Author:Administrator:PHA::us:realcme:0");pageTracker._setDomainName("realcme.com"); pageTracker._setAllowLinker(true);pageTracker._trackPageview();} catch(err) {}</script> certifications/ certifications2/ footers/ templates/ ?> </div></div> <!-- /#page-inner, /#page --> <?php /Applications /Library /Network /System /Users /Volumes /bin /cores /dev /etc /home /installer.failurerequests /net /private /sbin /tmp /usr /var <!-- certificates.txt certifications certifications2 directories.txt directories2.txt footers footers.txt iowa.php jon.sh migrate.sh migration_certs.sh migration_template_format.sh myshell.sh out.log permission templates templates.txt templates_footer.txt test.sh themplate_migration.sh - JavaScript Starts Here - certificates.txt certifications certifications2 directories.txt directories2.txt footers footers.txt iowa.php jon.sh migrate.sh migration_certs.sh migration_template_format.sh myshell.sh out.log permission templates templates.txt templates_footer.txt test.sh themplate_migration.sh --> <script type="text/javascript" src="/cms/sites/all/themes/zen/paradigmtheme/js/custom-main.js"></script> <!--script type="text/javascript" src="<?=$base_url;?>js/custom-main.js"></script--> <script type="text/javascript" src="<?=$base_url;?>js/superfish.js"></script> <script type="text/javascript" src="<?=$base_url;?>js/scrollWatch.js"></script> <script> jQuery(document).ready(function () { jQuery('.tt-parallax-text').fadeIn(1000); //delete this to remove fading content var $window = jQuery(window); jQuery('section[data-type="background"]').each(function () { var $bgobj = jQuery(this); jQuery(window).scroll(function () { var yPos = -($window.scrollTop() / $bgobj.data('speed')); var coords = '50% ' + yPos + 'px'; $bgobj.css({ backgroundPosition: coords }); }); }); }); </script> certifications/ certifications2/ footers/ templates/ ?>
